pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                echo "building..."
                dir("consuming-rest"){
                    pwd
                    sh './gradlew build'
                }
            }
        }
        stage("deploy"){
            steps{
                echo "deploying..."
                dir("consuming-rest"){
                    sh "java -jar build/libs/consuming-rest-0.0.1-SNAPSHOT.jar"
                }
            }
        }
    }
}