pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                echo "building..."
                sh './gradlew build'
            }
        }
        stage("deploy"){
            steps{
                echo "deploying..."
                sh "java -jar build/libs/consuming-rest-0.0.1-SNAPSHOT.jar"
            }
        }
    }
}